# This is a basic workflow to help you get started with Actions

name: Integración y entrega continua

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    env:
      nombres : "Josue Eduardo"
      apellidos: "Vilca Huayta"
      edad: "21"


      user: ${{ secrets.USER}}
      password: ${{ secrets.PASSWORD }}
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4



      # Runs a set of commands using the runners shell
      - name: presentación
        run: |
          echo mi nombre es $nombres $apellidos
          echo mi edad es ${{env.edad}} años

        # Runs a single command using the runners shell
      - name: Datos Generales
        run: echo “carrera de ingeniería de sistemas”


        # Runs a set of commands using the runners shell
      - name: variables de entorno secretas
        run: |
          echo usuario secreto es : ${{env.user}}
          echo contraseña secreta es : ${{env.password}}

      - name: variables de entorno secretas
        run: |
          echo Variables publica: ${{vars.VERSION_DE_MI_PROYECTO}}

      
